version: 2
updates:
- package-ecosystem: gomod
  directories:
    - "/"
    - "/testdata/validate/foo"
  schedule:
    interval: "monthly"
- package-ecosystem: "github-actions"
  directories:
    - "/" # == /.github/workflows/
  schedule:
    interval: "monthly"