version: "2"
formatters:
  enable:
    - gofmt
    - gci
  settings:
    gofmt:
      simplify: true
    gci:
      sections:
        - standard
        - default
        - localmodule
linters:
  default: standard
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false