# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest" ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        # use the version of Go specified in go.mod
        go-version-file: go.mod

    - name: Linting
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest

    - name: Test
      run: go test -v -race ./...
